stages:
  - scan

variables:
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

scan_todos:
  stage: scan
  image: python:3.9  # Use a Docker image with Python and pip
  script:
    - pip install requests
    - python CD/scan_todos.py > todos.txt
    - python CD/create_gitlab_issues.py
  only:
    - main